### ISSUE TITLE
feat: Migrate plugin to `github.com/cloudquery/plugin-sdk/v2`

### ISSUE THREAD

**Issue by candiduslynx** [koltyakov/cq-source-sharepoint#19]
Hello!
We've recently updated plugin-sdk to v2 (includes migration to Apache Arrow for the destination side).

Currently, no major updates to the source side were made.

Here's an easy step-by-step workflow that will allow you to migrate the code easily & efficiently:
1. Install [gomajor](https://github.com/icholy/gomajor)
2. `gomajor get github.com/cloudquery/plugin-sdk/v2`
3. add `replace` for `github.com/apache/arrow/go/v12` (see `github.com/cloudquery/plugin-sdk/v2` [`go.mod`](https://github.com/cloudquery/plugin-sdk/blob/main/go.mod))
4. `go mod tidy && go get -t -d ./... && go mod tidy && go mod vendor`
5. `make gen lint test` (if the appropriate targets exist)

**Comment by koltyakov** [comment]
Thank you @candiduslynx!
Migrated to plugin-sdk to v2.
Tested, no issues found.

**Comment by koltyakov** [comment]
@candiduslynx, I'm testing with updated destinations plugins such as SQLite v2.0.0 or PostgreSQL v4.0.0 and getting the error:

> is missing column _cq_id. please consider upgrading source plugin

With older version of destination plugins it works.

Could I miss something while updating to plugin-sdk/v2?

**Comment by candiduslynx** [comment]
@koltyakov try with CLI 2.5.3

**Comment by koltyakov** [comment]
@candiduslynx I was already using the latest (cloudquery/tap/cloudquery 2.5.3 already installed). 
It is something else.

**Comment by koltyakov** [comment]
It's seems not on my end. I tried the following as an experiment:

- took a configuration of postgre -> sqlite which worked before, 
- updated potgresql source to v1.0.8 which uses plugin-sdk v2, 
- updates sqlite destination to v2.0.0 which also migrated to plugin-sdk v2, 
- and also receiving the same error:

```bash
Starting migration with 1 tables for: coop-prod (postgresql@v1.0.8) -> [coop-local (sqlite@v2.0.0)]
Error: failed to sync v1 source coop-prod: failed to migrate source coop-prod (postgresql@v1.0.8) on destination coop-local (sqlite@v2.0.0) : failed to call Migrate: rpc error: code = Unknown desc = table artist is missing column _cq_id. please consider upgrading source plugin
```

Tried not only SQLite destination but also PostgreSQL with v2, same issue.

The error could be connected with incremental mode and throughs from plugins/destination/plugin.go

@yevgenypats maybe you know show could check this on your end, seems that it's global thing effected with plugin-sdk v2.

**Comment by yevgenypats** [comment]
> It's seems not on my end. I tried the following as an experiment:
> 
> * took a configuration of postgre -> sqlite which worked before,
> * updated potgresql source to v1.0.8 which uses plugin-sdk v2,
> * updates sqlite destination to v2.0.0 which also migrated to plugin-sdk v2,
> * and also receiving the same error:
> 
> ```shell
> Starting migration with 1 tables for: coop-prod (postgresql@v1.0.8) -> [coop-local (sqlite@v2.0.0)]
> Error: failed to sync v1 source coop-prod: failed to migrate source coop-prod (postgresql@v1.0.8) 
>   on destination coop-local (sqlite@v2.0.0) : failed to call Migrate: rpc error: 
>   code = Unknown desc = table artist is missing column _cq_id. please consider upgrading source plugin
> ```
> 
> Tried not only SQLite destination but also PostgreSQL with v2, same issue.
> 
> The error could be connected with incremental mode and throughs from plugins/destination/plugin.go
> 
> @yevgenypats maybe you know show could check this on your end, seems that it's global thing effected with plugin-sdk v2.

Taking a look

**Comment by erezrokah** [comment]
Hi @koltyakov, thanks for reporting this issue. Can you try with version `v2.0.2` of the SQLIte plugin? The issue should be fixed in that version

**Comment by erezrokah** [comment]
Thanks for reporting @andrew-koltyakov-wmg, I believe https://github.com/cloudquery/cloudquery/pull/10202 should fix it

**Comment by erezrokah** [comment]
Thanks for confirming @koltyakov! I think the forced migration is expected since we switched to using `bool` type for booleans instead of `int`. SQLite doesn't support that natively by the Go library we use handles it https://github.com/mattn/go-sqlite3/blob/edc3bb69551dcfff02651f083b21f3366ea2f5ab/doc.go#L21
