### ISSUE TITLE
csptl tool issue

### ISSUE THREAD

**Issue by FredBl79** [koltyakov/cq-source-sharepoint#20]
Hi,

Thanks a lot for this Sharepoint Connector ! just doing some internal test sucessfully

Found 2 issues with csptl tool

- destination: should be renamed to destinations:
- tables: is now mandatory 

Regards
Fred

**Comment by koltyakov** [comment]
Thank you @FredBl79,

Pushed v1.8.1 which fixes these issues.

Please check when you have some time.

**Comment by FredBl79** [comment]
thanks @koltyakov , will test it for a next config

**Comment by koltyakov** [comment]
Going to close the ticket.
