### ISSUE TITLE
Sharepoint to Mysql : data randomly pushed to mysql table

### ISSUE THREAD

**Issue by FredBl79** [koltyakov/cq-source-sharepoint#21]
Hi,

I have seen during my test phase that the rows are not pushed at every sync

I have attached the different scenarios 

[cloudquery - TableExistingNoRowsadded.log](https://github.com/koltyakov/cq-source-sharepoint/files/11475537/cloudquery.-.TableExistingNoRowsadded.log)
[cloudquery - TableExistingRowsAdded.log](https://github.com/koltyakov/cq-source-sharepoint/files/11475538/cloudquery.-.TableExistingRowsAdded.log)
[cloudquery - TableCreatedNoRowsadded.log](https://github.com/koltyakov/cq-source-sharepoint/files/11475539/cloudquery.-.TableCreatedNoRowsadded.log)
[cloudquery - TableCreatedRowsadded.log](https://github.com/koltyakov/cq-source-sharepoint/files/11475540/cloudquery.-.TableCreatedRowsadded.log)

Is it possible to use the sync to do a daily update ?

Thanks
Fred

**Comment by koltyakov** [comment]
I'm not sure I'm following. Are you saying you end up with different results syncing the same source (a single SharePoint list data as I can see from the logs)?

Can you separate it from a potential MySQL destination issue and try to sync to sqlite v2.0.4 for instance?

What's the version of MySQL destination plugin you're using?

The results of the sync when you run first or any upcoming sync should always align destination with source (creating new, deleting removed and updating changed items), and running sync on a schedule basis is the common scenario. 

I'm not able to repro, e.g. I have 1000 items in a list.
- Initial sync creates 1000 items in a destination
- Removing items ends up with -N in a destination
- Adding items results with +N in a destination
- Updating items effects destination values

**Comment by koltyakov** [comment]
Maybe it's something within the destination plugin. I'll check how my sync scenarios effects in MySQL.

If it's destination plugin issue when should be asked to CloudQuery repo.

For the source plugins, the destinations are abstracted behind an interface so no difference is it a PostgreSQL or Snowflake or MySQL.

**Comment by koltyakov** [comment]
Going to close the ticket.
