### ISSUE TITLE
Migrate plugin to `github.com/cloudqeury/plugin-sdk/v4`

### ISSUE THREAD

**Issue by candiduslynx** [koltyakov/cq-source-sharepoint#22]

**Comment by koltyakov** [comment]
Migrated to v4.

**Comment by candiduslynx** [comment]
@koltyakov this looks great!

I also started porting the code to plugin-sdk/v4 & have some comments regarding the structure of the plugin.

I'll rebase the code to the latest `main` & make a PR with suggestions.

**Comment by koltyakov** [comment]
Thank you @candiduslynx! 

Yeah, upgrading the plugin was a bit tricky due to some structural changes and backwards incompatibility with v2. So what I did - scaffolded a blank new plugin and moved business logic also looking to some other plugins.

I'll check the suggestions.
