### ISSUE TITLE
Can this plugin get data when provided select sharepoint urls in format (doc_lib/folder_path) , instead of the entire list or doc lib of sharepoint

### ISSUE THREAD

**Issue by ssmails** [koltyakov/cq-source-sharepoint#28]
Can this plugin get data when provided select sharepoint urls in format (doc_lib/folder_path) , instead of the entire list or doc lib of sharepoint

**Comment by koltyakov** [comment]
A filter condition (e.g. by `FileLeafRef`) can limit items by path.
But it's not recommended as if your list reaches throttling limit (5000 items) such API request won't work.
It's better sync whole list and filter data on consumer end.
Another option is using [Search](https://github.com/koltyakov/cq-source-sharepoint?tab=readme-ov-file#search-queries).

**Comment by koltyakov** [comment]
Going to close it as answered.
